name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: install sdl dev
    - run: sudo apt update && sudo apt-get install libsdl2-2.0-0 && sudo apt install libsdl2-dev
    
